title: VulnServer Labs Docs
description: Official documentation for VulnServer Labs
baseurl: "/docs"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
permalink: pretty
